apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: multus-my-ran
  namespace: default
spec:
  upstream:
    repo: nephio-blueprints
    package: networking/multus-cni
  downstream:
    repo: nephio-my-ran
    package: multus-cni
  pipeline:
    mutators:
      - image: gcr.io/kpt-fn/apply-setters:v0.2
        configMap:
          cluster-name: my-ran
