apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: baseline-my-ran
  namespace: default
spec:
  upstream:
    repo: nephio-blueprints
    package: cluster-baseline
  downstream:
    repo: nephio-my-ran
    package: cluster-baseline
  pipeline:
    mutators:
      - image: gcr.io/kpt-fn/apply-setters:v0.2
        configMap:
          cluster-name: my-ran
          cluster-type: workload
          workload-type: ran
          site-id: site-ran-01
          cluster-repo-url: https://github.com/rehanfazal77/nephio-my-ran.git
          cluster-repo-branch: main
          storage-class-name: local-path
